### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by kelfink** [tkompare/chicagoflushots#5]
How do you perform the minimizing of the javascript?   I don't see a script to run to re-minify new versions.  There are a number of tools, I'm aware.  I thought in my branch I'd try to use the same one as the project originally has.

thanks!

**Comment by tkompare** [comment]
HI Kevin. I use CodeKit (I have version 2.7.1). It uses Uglify JS to do the minification. I think I'm using the default options, but see the attached screenshots for my settings. I hope this helps!

Side note: I think next update (this summer) I'm going to swap out the current map icons for this: https://design.google.com/icons/#ic_place I've never really loved the current pin design. I like the one from Google's Material Icon set much better.

<img width="1280" alt="screen shot 2016-03-07 at 8 41 31 pm" src="https://cloud.githubusercontent.com/assets/788638/13590414/4e514996-e4a5-11e5-9fa0-de7ecfc15818.png">
<img width="1280" alt="screen shot 2016-03-07 at 8 41 50 pm" src="https://cloud.githubusercontent.com/assets/788638/13590415/4e57ee9a-e4a5-11e5-9676-391de16b0f30.png">
<img width="1280" alt="screen shot 2016-03-07 at 8 42 06 pm" src="https://cloud.githubusercontent.com/assets/788638/13590416/4e5d76c6-e4a5-11e5-9813-f82a23fa53c6.png">
<img width="1280" alt="screen shot 2016-03-07 at 8 42 29 pm" src="https://cloud.githubusercontent.com/assets/788638/13590417/4e62d102-e4a5-11e5-9863-1d9fecce5952.png">
<img width="1280" alt="screen shot 2016-03-07 at 8 42 40 pm" src="https://cloud.githubusercontent.com/assets/788638/13590418/4e68df98-e4a5-11e5-9daa-216e0d8e7199.png">
